### ISSUE TITLE
open 이 안되는 이슈

### ISSUE THREAD

**Issue by jongmoon** [humy2833/FTP-Simple#1]
안녕하세요, @humy2833 

오늘 VS Code 에서 플러그인 설치하면서 알게 되었습니다.
정말 좋은 인터페이스를 가진 플러그인인 거 같습니다 ^^

다만 설정하면서 좀 난관에 부딛히게 되었는데요.

config 설정하고 open 하면,
다음과 같이 나옵니다.

![image](https://cloud.githubusercontent.com/assets/3255471/17244228/c4c691bc-55bb-11e6-8058-44318ea73f73.png)

혹시나 싶어 save 를 눌러봤는데 그건 또 동작하네요.

어떻게 동작시킬 수 있을런지 조언 부탁드립니다. ^^

**Comment by humy2833** [comment]
안녕하세요. 허접한 플러그인에 관심 가져주셔서 감사합니다.^^

open 이 안된다고 하셨는데요, config 설정시에 path 항목에 어떻게 작성하셨는지요?
지금 올려주신 이미지 상으로는 '/' 로 나오는데, 그럼 실제로 ftp 툴로 접속 했을때 remote 경로를 '/' 로 바꾸면 제대로 파일들이 나오나요??

그리고 save 는 동작한다고 하셨는데요, ftp 에 upload 하는 save 를 말씀하시는건가요??
save 가 된다면 open 도 되어야 하는데요....희한하네요.

저한테서 해당 증상이 재현이 되어야 어떤 버그인지를 알 수 있을텐데...ㅜㅜ
혹시 해당 ftp 서버 말고 다른 ftp서버 설정 추가로 가지고 계신건 없으신가요?
다른 서버도 그렇게 나오는지요.....

한번 다른 서버도 해보시고 안된다면 다시 한번 말씀해주세요~
감사합니다.

**Comment by jongmoon** [comment]
네. Parh 에 경로는 / 로 처리했고. 하위 경로로 변경도 해보았으나 마찬가지입니다. 희한하게 업로드는 잘 되더라구요 ^^;

ftp sync 라는 걸 아쉬운데로 사용하게 되었습니다. 나중에 다시 한번 시도해보고 말씀드리겠습니다. 답변 주셔서 감사합니다 ^^

**Comment by humy2833** [comment]
안녕하세요.
이제서야 답변을 드리네요. 
그동안 이 문제를 잡으려고 끙끙 댔는데 이제야 해당 문제점을 찾은거 같아서 답변 드립니다.
시간이 되시면 다시 한번 설치하셔서 확인 한번 부탁드립니다.(__)
감사합니다~!
