### ISSUE TITLE
Text file encoding issue

### ISSUE THREAD

**Issue by neobutter** [humy2833/FTP-Simple#102]
안녕하세요. (Github에서 한글로 이슈 올려보는건 처음이네요 ^^)

저 역시 다른분처럼 EUC-KR 때문에 문제가 발생하네요.
일단 제가 Test 해 본 부분은 다음과 같습니다.

* 다운로드 된 Text 파일 Encoding 확인
   -  윈도우 메모장에서 다운로드 된 파일 확인 (다른이름으로 저장을 해 봤을때, UTF-8이 아닌 ANSI로 표기)

* 다운로드 된 파일을 짧은 경로에 복사해서 열어보기
   - 정상적으로 EUC-KR로 열림 (파일이 UTF-8로 저장되지는 않는것으로 보입니다.)
   (단순히 경로가 긴 파일이라서 읽어가는곳에 문제가 있는것으로 추측되네요)

* ftp-simple.remote-workspace 설정 적용해보기
   - 설정후에 개발자 도구에는 개발자님이 추가해 놓은신 로그에 제가 설정한 경로가 잘 찍히는데, 막상 해당 경로가 아닌 Default 경로에 파일이 다운로드 되어집니다.
> [Extension Host] REMOTE_WORKSPACE_PATH= D:\temp

제가 어떤 방법을 더 취해보면 될까요?

**Comment by humy2833** [comment]
안녕하세요
ftp-simple.remote-workspace 설정은 원격으로 파일을 열때(remote dir....)에만 적용되는 경로입니다.
현재 제대로 여실려면 Download 해서 여시는 방법밖에는 없겠네요
Open 으로 해당 파일을 열려면 제가 수정하는 작업이 들어가야 할것 같습니다.

**Comment by neobutter** [comment]
시간이 나신다면 수정 부탁 드립니다. ^^

그리고 좀 더 테스트 한 결과 알려드립니다.

1. 전체 Path 길이는 큰 상관이 없는것으로 보입니다.
2. 그것보단 지금 Temp로 사용하고 있는 폴더의 퍼미션이 문제가 되는 것 같습니다.
C:\Users\{Account}\AppData\Roaming\Code\User 하위로 파일이 생성되면 비정상적으로 되며...
저 User 폴더 말고 다른 폴더를 만들어서 진행하면 특별히 문제가 없는것 같습니다.

3. 가능하다면 %temp%를 사용하는것도 방법일 수 있겠네요.

감사합니다.

**Comment by humy2833** [comment]
ftp-simple.remote-workspace 에 설정한 경로로 열리게 수정하였습니다.
0.5.8 을 받아보세요

**Comment by neobutter** [comment]
완전 잘 열립니다. ^^ 
빠른 버전 업 감사합니다.

**Comment by workman729** [comment]
리눅스는 어떻게 합니까? 자동으로 c:가 들어가던데...!
