### ISSUE TITLE
Endless connecting FTP

### ISSUE THREAD

**Issue by qaczy** [humy2833/FTP-Simple#104]
I've faced some problem with connecting server. In output I got just:

> > [2017-10-18 10:04:30] work - FTP Connecting...

Which doesn't end. I don't have any errors.
I guess I set correctly data. 
```
"name": "work",
		"host": "dev.work.com",
		"port": 21,
		"type": "ftp",
		"username": "username",
		"password": "password",
		"path": "/public_html/project",
		"autosave": true,
		"confirm": true
```
Also I tried: 
`"path": "dev.work.com/public_html/project"`

I'm working with the 1.18.0-insider (i tried on stable - the same problem), ftp-simple 0.5.8, os Win10.

**Comment by humy2833** [comment]
Please check the ftp connection information.
Are the host and port correct?
Is this information accessible from other FTP tools?

**Comment by qaczy** [comment]
Yup, I can access from Filezille, Brackets via Synapse and Atom via Ftp-remote-edit.
I just made connection via SFTP extension on VS code. So i think it's not problem in connection information :( 

I put wrong password and I got 

> 530 Please login with USER and PASS

So maybe that ftp server is ignoring FTP-simple?

**Comment by qaczy** [comment]
I tried sftp protocol and works fine every command works smooth without any problems :)
Don't know why with ftp protocol extension can't reach server :( 
Thank you for your time and bringing such essential tool
