### ISSUE TITLE
SFTP connection problem

### ISSUE THREAD

**Issue by lorenzonet** [humy2833/FTP-Simple#107]
I've configured a connection to an internal sftp server as below:

`	{
		"name": "AUTH-DEV.LOCALE",
		"host": "auth-dev.locale",
		"port": 22,
		"type": "sftp",
		"username": "myusername",
		"password": "mypassword",
		"path": "/",
		"autosave": true,
		"confirm": true
	},`

When I try either to download or open a file I don't get any errors but nothing happens.
Any clues? Is there any log file?
The settings are correct, I've tried with filezilla.

Lorenzo

**Comment by toniupper** [comment]
I've same problem with FTP connection !!

**Comment by lorenzonet** [comment]
![filezilla](https://user-images.githubusercontent.com/16530670/32849282-ffc1f49e-ca2e-11e7-8f34-e20a2e92599a.jpg)

I'm aware that the hostname is different from what I wrote earlier, I shortened it intentionally, in the original file setting is correct.

**Comment by imnickvaughn** [comment]
I'm having a similar problem at the moment.  That is if "nothing happens" means its connecting, i can navigate through and see the files but once I try to open them the code is not visible
![image](https://user-images.githubusercontent.com/24948723/33440069-fcb86dfc-d5bc-11e7-8e80-c2baad64bad9.png)

**Comment by chchoiw** [comment]
I had the same problem before, my problem is that the server is set "PasswordAuthentication no" by default.

Here is my solution :
vim /etc/ssh/sshd_config -> #PasswordAuthentication no -> PasswordAuthentication yes
or using sftp which has the option can be set. ( "interactiveAuth": true)

I just wonder if "interactive authentication " can also be set in ftp-simple?

**Comment by lorenzonet** [comment]
You're right Chchoiw, I've changed PasswordAuthentication and now it works fine.

**Comment by pkreipke** [comment]
Hmm. ISP doesn't allow change to the value of PasswordAuthentication in sshd_config. Is there another workaround?
