### ISSUE TITLE
리눅스에선 remote-workspace를 어떨게 적용합니까?

### ISSUE THREAD

**Issue by workman729** [humy2833/FTP-Simple#118]
이번에 에디터를 빠궈볼까 하는데 remote-workspace 적용이 리눅스에선 안되는가요?
ftp 오픈시 euc-kr 변경이 안 되는데 리눅스에선 안 되는 건가요?

처음에 c:/가 자동으로 들어가던데 이후엔 안 그렇군요!

환경은 페도라, gnome-3.26 이구요! 적용은 설정에서 다음과 같이 적용하였습니다.

"ftp-simple" : {
"remote-workspace" : "/home/user/.vscode/remote",
"remote-workspace-load-all" : true
}

혹, 제가 몰라서 그런것이라면 과감 없이 말씀해 주시기 바랍니다.

**Comment by humy2833** [comment]
리눅스에서 테스트를 해보지 않아서 자세히는 모르겠지만 적용이 안되진 않을것 같습니다.
그리고 설정도 이상없이 하신거 같고요.
"remote-workspace" 로 프로젝트를 열었을때 파일들이 "/home/user/.vscode/remote" 안으로 받아지지 않던가요??
그리고 그 파일을 열때 utf-8로 열리고 euc-kr 로 변경돼서 열고 싶으시다는건가요?

**Comment by workman729** [comment]
네, 그렇습니다. 엔코딩을 적용해 보고 싶은데 말씀의 뉘앙스로 보니 ftp 설정에 프로젝트도 적용하라는 뜻을 가진 것으로 추측되어 집니다.

말씀 처럼 적용한 디렉토리에 다운로드 되질 않아서 그대로  utf-8로 열립니다.
제가 바르게 추측한 것인지요?

**Comment by humy2833** [comment]
커넥션이 연결되어 있는 상태라면 설정을 다시 로딩하지 않습니다^^;
아무튼 잘 된다고 하시니 다행이네요
감사합니다.
