### ISSUE TITLE
Changing language mode of file opened from workspace removes content

### ISSUE THREAD

**Issue by stefan-scholl** [humy2833/FTP-Simple#12]
A CMS uses the file extension ".module" for PHP code. I used "remote directory open to workspace" and opened a file "Helloworld.module" from the workspace, changed the language mode from "Text" to "PHP" and the text is gone. Blank page.

Now the fun part: When I use "open the file directly from FTP server" I can change the language mode without any problems.

**Comment by humy2833** [comment]
Please accept again the latest version. (0.4.2)
Thanks.
