### ISSUE TITLE
건의 사항입니다.

### ISSUE THREAD

**Issue by wangtae** [humy2833/FTP-Simple#130]
좋은 프로그램 개발해 주셔서 감사합니다.

이번 건의 사항은 특정 환경에서만 발생하는 것인지 FTP-Simple 자체의 문제인지 모르겠지만 제가 사용중인 환경을 기반으로 설명드릴게요.

제 예상은 FTP-Simple를 VSCode에서 [확장모듈]로 인식하는 부분에서의 문제이지 않을까 생각됩니다.

1. VSCode 설정을 동기화하는 [Syncing]라는 확장 프로그램을 사용중인데, FTP-Simple의 config 파일은 동기화에서 제외됩니다.

2. [사용자 설정] 에서 아래와 같이 사용자 정의하여 사용중입니다. ("ftp-simple": { 이 부분이 118 라인)

   "ftp-simple" : {
        "remote-workspace" : "c:/Users/User1/OneDrive/VSCode/sftp",
        "remote-workspace-load-all" : false
    },

   사용 자체는 전혀 문제가 없으나 [사용자 설정] 파일을 열면 하단패널의 [문제] 탭에서 에러 메시지가 표시됩니다. 

   에러 내용은 다음과 같습니다.  

   settings.json c:\Users\User1\AppData\Roaming\Code\User
      Unknown configuration setting (118, 5)

**Comment by humy2833** [comment]
해당건은 무시하셔도 됩니다.
VSCode 자체에서 지원하는 옵션이 아니면 모두 다 그렇게 표시합니다.
