### ISSUE TITLE
ftp-simple uploads all files in VS Code 1.24.0

### ISSUE THREAD

**Issue by diakonos** [humy2833/FTP-Simple#143]
I just updated VS Code today to version 1.24.0, and now ftp-simple always uploads all files instead of just the open file.

**Comment by SiddhyN** [comment]
I have the same bug using keyboard shortcuts ([ctrl] + [shift] + s).

With the context menu the backup file by file works correctly

**Comment by metalfox6383** [comment]
Yes! Me too! It hapend after VSCode update!

**Comment by humy2833** [comment]
I have now fixed it to version VSCODE-1.24.0.
Please update to version 0.6.4.

**Comment by diakonos** [comment]
Yep, it's fixed for me. Thanks for the quick fix!
