### ISSUE TITLE
How do you use this?

### ISSUE THREAD

**Issue by jsa41394** [humy2833/FTP-Simple#15]
Hi,

No idea how to sync with FTP server.

Your instructions say to setup the FTP config file, which works, but then none of the commands are pulling the files (or doing anything). I opened a new folder and tried all of the commands in different orders (e.g.  create directory -> remote directory open -> download -> diff -> save ... Nothing)

Did not see any error messages or file changes, so have no idea how to use

**Comment by humy2833** [comment]
This module will let Jean synchronization with FTP servers and automatically.
Similar to a typical FTP program.
Open the file on the server and can be modified directly, you can upload and downloads.
