### ISSUE TITLE
if nothing changed in the file , the  press CTRL Z will empty the file content

### ISSUE THREAD

**Issue by zhenlonghe** [humy2833/FTP-Simple#158]

**Comment by guppy42** [comment]
This is a super anoying bug, especially as hitting ctrl-z when you meant to hit ctrl-shift-\ is entirely possible.

**Comment by guppy42** [comment]
Seems to be related; When you open a file is is shown in cursive(new/unsaved) in the title tab and opening another file from the explorer will replace it - unless you save it, even with no changes.
