### ISSUE TITLE
 Blank Files issue VScode january 2019 update

### ISSUE THREAD

**Issue by muscaiu** [humy2833/FTP-Simple#181]
I just updated VSCode and ftp-simple doesn't work properly anymore.
It seems to load the files and folder structure, but **all files are empty**.
I didn't change anything, just updated VScode. Is it just me?

![empty](https://user-images.githubusercontent.com/11426309/52618036-5b234e00-2ea6-11e9-8525-4f5845876cbf.png)

![config](https://user-images.githubusercontent.com/11426309/52618042-5fe80200-2ea6-11e9-9c91-d3b36e182acd.png)

**Comment by Peric1e** [comment]
Its not working with the new version of vscode

**Comment by humy2833** [comment]
We apologize for any inconvenience.
There was a problem with the internal ftp module that was being used when VSCode version 1.31 was upgraded.
Please use VSCode downgrade (1.30) while correcting the problem.

**Comment by muscaiu** [comment]
ftp2 worked!
