### ISSUE TITLE
command '...' not found

### ISSUE THREAD

**Issue by dechsiri** [humy2833/FTP-Simple#184]
I don't known what's problem but It happens after I updated to 0.70

**Comment by humy2833** [comment]
It is an error in other plugins.
Find and disable or remove the plugin that caused the error.

**Comment by dechsiri** [comment]
I try to disable all of other plugins except ftp-simple 
It's still command not found

**Comment by dechsiri** [comment]
now, I updated visual studio code. It's works

Thanks,
