### ISSUE TITLE
Use of privateKey

### ISSUE THREAD

**Issue by spirrello** [humy2833/FTP-Simple#2]
Hi,

I'm trying to use the following configuration but for some reason it doesn't launch the connection to the server.  Do you see anything wrong?

[

```
{
    "name": "c7-1",
    "host": "c7-1",
    "port": 22,
    "type": "sftp",
    "username": "spirrello",
    "password": "",
    "privateKey": "/Users/spirrello/.ssh/id_rsa.pub",
    "path": "/home/spirrello"
}
```

]

**Comment by humy2833** [comment]
No '.pub' file.
The only private key.
ex) id_rsa, id_rsa.pub   =>  id_rsa
Maybe... =>  "/Users/spirrello/.ssh/id_rsa"

**Comment by spirrello** [comment]
Thanks for the quick response.  I tried that as well but nothing happens
when I correct it.

[
{
"name": "myserver.local",
"host": "myserver.local",
"port": 22,
"type": "sftp",
"username": "spirrello",
"path": "/home/spirrello",
"privateKey" : "/Users/spirrello/.ssh/id_rsa"
}
]

**Comment by humy2833** [comment]
You public key did was added to the authorized_keys file on the server?
Can you use ssh command to server? 
ex) ssh your_account@myserver.local

**Comment by spirrello** [comment]
Yes I can ssh freely to the target server without a password.

**Comment by jhit** [comment]
Hello. I have similar issues to get my sftp connection working. Is there any error output ot log I can watch to get a clue what is going on?

**Comment by humy2833** [comment]
ssh connect used the 'ssh2 module'.
(https://www.npmjs.com/package/ssh2)
Would you like to try a test using this module?

**Comment by jhit** [comment]
> Would you like to try a test using this module?
Shure, how can I do this?

**Comment by hrenki** [comment]
I can't get it to work either... looks like cant access private key... mine was in "C:/Users/User/id_rsa" and nothint... it says "ftp connecting..."

**Comment by hrenki** [comment]
ok, i get it to work now. 
problem was that i did not entered any "passphrase" for key
added this to connection config and all seems to be working ok:
"passphrase": "",

**Comment by humy2833** [comment]
ok.
Please accept again the latest version.(0.4.11 or higher)

**Comment by casematrix** [comment]
Are there any plans to support storing the private key in the OS's keychain, or encrypting it at rest in the config file, or at least prompting for it instead of requiring that it be left in plaintext in the config file?

**Comment by aali361** [comment]
How can I specify private key path in windows?
my private key path is: C:\Users\me\.ssh\id_rsa.pub.
is this right?
```
[
	{
		"name": "myweb",
		"host": "ip",
		"port": 1111,
		"type": "sftp",
		"username": "root",
		"privateKey": "C:\\Users\\me\\.ssh\\id_rsa",
		"path": "/var/www/",
		"autosave": true,
		"confirm": false
	}
]
```
This give me error that say 

> Connect fail : Error: All configured authentication methods failed
