### ISSUE TITLE
Not working after update

### ISSUE THREAD

**Issue by pjam** [humy2833/FTP-Simple#20]
Hi.

After this last update, I can't get the plugin to work. I had the files opened in the workspace from before, but now they were opening empty.
Tried to reconfigure the plugin, now I can't get the files to workspace. According to output, it gets info from some files, but then stops.

P.S. using sftp

**Comment by josevill** [comment]
Same here, i thought it was only me because my crappy WiFi but.. Let's see if we can get it fixed soon

**Comment by pjam** [comment]
some more info from developer tools

![image](https://cloud.githubusercontent.com/assets/850139/20606401/8c653792-b268-11e6-89fd-7207518e8c0f.png)

**Comment by humy2833** [comment]
Sorry.
Please accept again the latest version.(0.4.5 or higher)
Thank you.

**Comment by pjam** [comment]
Yes, it is working now. Thanks

**Comment by pjam** [comment]
Still not working right. Just some files are downloaded, not all project tree

**Comment by dnohr** [comment]
I'm using 0.4.9 and after the latest updates my FTP upload stopped to work. Anyone else has upload issues with the new updates? It was working great before.

**Comment by humy2833** [comment]
oh sorry and thanks.
Please accept again the latest version.(0.4.10 or higher)

**Comment by pjam** [comment]
Still not working properly...  :(

Can't you create a .vsix file for the working version from last week for us to keep working while you work on it?

**Comment by humy2833** [comment]
What exactly can not you do?
please let me know step by step.

**Comment by dnohr** [comment]
I can confirm that the update 0.4.10 solved my upload issue, thanks!

**Comment by pjam** [comment]
Remote directory open to workspace only gets somes files then stops without retrieving all files in server.

**Comment by humy2833** [comment]
Can you check for console error messages and let me know?
You can see in the development console.

**Comment by pjam** [comment]
Here you go...
![image](https://cloud.githubusercontent.com/assets/850139/20798206/f2956d94-b7d5-11e6-8d03-aa0aea4a5474.png)

**Comment by humy2833** [comment]
Thanks.
That's what I expected.
It has been modified.
(We recovered to its original state. So the speed is slow....)

**Comment by pjam** [comment]
Thanks for the change. Now it is working ok again.

Besides that, isn't possible to add a Create file command, through ftp?

Thanks again

**Comment by humy2833** [comment]
It is possible with the "Remote directory open to workspace" function.
Simply create and save the file in the file explorer.
