### ISSUE TITLE
There is an error that files received from ftp cannot be updated at 0 kb. ftp에서 받은 파일들이 전부 0kb입니다.

### ISSUE THREAD

**Issue by hwanam1111** [humy2833/FTP-Simple#213]
Hello.

I've been using the ftp simple in recent months and I'm going to use it today.

Files received from ftp simple stopped at 0 kb.

When you download a file from a program such as File Zilla, the file appears to be OK, but this error occurs when you try to work with the ftp simple.

And if you select another menu related to ftp simple in that state,

command 'ftp.config' not found

An error will be generated.

안녕하세요.

최근 몇달동안 ftp simple을 잘 쓰다가 오늘 사용하려 하니

ftp simple에서 받은 파일들이 0kb 에서 멈췄습니다.

파일질라같은 프로그램에서 파일 다운로드시 파일은 정상으로 나오는데, ftp simple에서 작업하려고 하니 이런 오류가 나옵니다.

그리고 그 상태에서 ftp simple 관련 다른 메뉴를 선택하면

command 'ftp.config' not found

해당 오류가 나옵니다.

**Comment by JunAh** [comment]
저도 같은 오류가 나옵니다
vscode를 지웠다 깔아봐도 command 'ftp.config' not found 오류가 나오네요 시간도 비슷합니다

**Comment by mois-ilya** [comment]
Please, write your issue title in english.
I have the same problem. So `ftp.save, ftp.open` also not located.
  
![image](https://user-images.githubusercontent.com/7352569/66030356-d5721280-e509-11e9-97ca-bbafd85054e7.png)

**Comment by juniya0509** [comment]
> 저도 같은 오류가 나옵니다
> vscode를 지웠다 깔아봐도 command 'ftp.config' not found 오류가 나오네요 윗 분과 오류난 시간도 비슷합니다

아직까지 해결 안되고 다른분들도 같은오류가 발생되는걸 보니 아직 FTPSIMPLE 문제같네요 ㅠ

지금은 되시나요?

**Comment by hwanam1111** [comment]
> Please, write your issue title in english.
> I have the same problem. So `ftp.save, ftp.open` also not located.
> 
> ![image](https://user-images.githubusercontent.com/7352569/66030356-d5721280-e509-11e9-97ca-bbafd85054e7.png)
> 
> Think it can be related #184

OK. I Changed title.
I hope it'll be settled soon.
T_T..

**Comment by hwanam1111** [comment]
Downgrading version from 0.7.1 to 0.7.0 will work.

#214

**Comment by hwanam1111** [comment]
> 저도 같은 오류가 나옵니다
> vscode를 지웠다 깔아봐도 command 'ftp.config' not found 오류가 나오네요 윗 분과 오류난 시간도 비슷합니다

FTP SIMPLE 버전을 0.7.1에서 0.7.0으로 다운그레이드하면 작동됩니다.

방금 해보니까 되네요.

**Comment by JunAh** [comment]
> > 저도 같은 오류가 나옵니다
> > vscode를 지웠다 깔아봐도 command 'ftp.config' not found 오류가 나오네요 윗 분과 오류난 시간도 비슷합니다
> 
> FTP SIMPLE 버전을 0.7.1에서 0.7.0으로 다운그레이드하면 작동됩니다.
> 
> 방금 해보니까 되네요.

아하 ㅠㅠ 모듈에 문제가 있던게 맞군요 감사합니다

**Comment by humy2833** [comment]
I'm very sorry.
Please upgrade to version 0.7.2.
