### ISSUE TITLE
Version 0.7.1

### ISSUE THREAD

**Issue by anderenbenutzer** [humy2833/FTP-Simple#214]
Hey, I just upgraded to the latest version 0.7.1. Unfortunately I got: "command 'ftp.remote.workspace.open' not found - none of the commands are working. Downgraded to the working version 0.7.0...

**Comment by humy2833** [comment]
I'm very sorry.
Please upgrade to version 0.7.2.

**Comment by anderenbenutzer** [comment]
> I'm very sorry.
> Please upgrade to version 0.7.2.

Hi. Please do a test first. 0.7.2 isn't working properly. It shows files as directories! 
See screenshot:
https://www.dropbox.com/s/7yr7g914c4yq09k/Simple_FTP.jpg?dl=0
