### ISSUE TITLE
Does not show directories v. 0.7.1

### ISSUE THREAD

**Issue by athemix** [humy2833/FTP-Simple#215]
After the update does not show the directory on the remote server. Displays only files. I had to roll back

**Comment by aykutceylan** [comment]
I have same problem!

**Comment by clarkexcore** [comment]
> Same, you can [rollback to 0.7.0](https://stackoverflow.com/questions/42626065/vs-code-rollback-extension-install-specific-extension-version#answer-53755378)

You are a godsend. Thank you.

**Comment by DynamicProgramr** [comment]
Make sure you save a copy of your ftp-simple-temp.json file (the file that holds you FTP connection into).  In my case, when I rolled back, the file was set back to the default. :(

**Comment by humy2833** [comment]
I'm very sorry.
Please upgrade to version 0.7.2.
