### ISSUE TITLE
Commands Not Working

### ISSUE THREAD

**Issue by tugbanurbuyukkaraca** [humy2833/FTP-Simple#216]
The plugin is corrupted after the update. I get the following errors when I want to run commands. And folders dont open

command 'ftp.config' not found
command 'ftp.open' not found

**Comment by clarkexcore** [comment]
I am also experiencing these same issues. Tried uninstalling and reinstalling it. Completely uninstalled VS Code. Followed the instructions here https://stackoverflow.com/questions/54781368/what-is-command-ftp-config-not-found-error-in-visual-studio-code-vscode-ft they also did not work.

**Comment by alexspyr** [comment]
Same problem. It was working yesterday.

**Comment by starspro** [comment]
Same problem

**Comment by alexspyr** [comment]
I am sharing the error in the console of the developers tools _(Help -> Toggle Developer Tools)_

![vscode_ftpsimple](https://user-images.githubusercontent.com/14580634/66067235-da5bb400-e553-11e9-9ce8-6d854703c573.png)

**Comment by cpgb85** [comment]
same problem.

**Comment by alexspyr** [comment]
**Good news** 
Rolling back to a previous version worked for me.

https://stackoverflow.com/questions/42626065/vs-code-rollback-extension-install-specific-extension-version#answer-53755378

_Back up your config file just to be sure, because while I was trying things to get it to work I deleted the plugin and I lost the saved sites on the config file._

**Comment by cpgb85** [comment]
> **Good news**
> Rolling back to a previous version worked for me.
> 
> https://stackoverflow.com/questions/42626065/vs-code-rollback-extension-install-specific-extension-version#answer-53755378
> 
> _Back up your config file just to be sure, because while I was trying things to get it to work I deleted the plugin and I lost the saved sites on the config file._

I can verify this works. But this is merely a band aid. This needs to be fixed on the most current version.

**Comment by lamaro** [comment]
I had to rollback to a previous version too.

**Comment by bmpf** [comment]
same problem

**Comment by nicschwartz** [comment]
I've had the same issue in a course I'm teaching. Most students lost their config files and had to rebuild them -- not a big deal, but slightly stressful as we head into mid terms! 
We rolled back to version 0.7.0 and have no issues.

**Comment by humy2833** [comment]
I'm very sorry.
Please upgrade to version 0.7.2.
