### ISSUE TITLE
ftp-simple don't recognize directory

### ISSUE THREAD

**Issue by ValmirGonzagaCosta** [humy2833/FTP-Simple#217]
Hi everyone,

I have ftp-simple installed in a vscode. When I connect in a remote server, ftp-remote don't recognize the directory. They understand my directories as a file.  The ftp connection work well, but I can't open my file into this directory, becouse they don't recognize with a directory.
![ftp-file](https://user-images.githubusercontent.com/56134192/66157348-fd40a380-e5f9-11e9-9608-ee663532ee1a.png)

Another problem is that I cant' see the ftp-simple in the "File - Preferences - Settings" to configure the options below:

"ftp-simple" : {
    "remote-workspace" : "c:/remote-workspace",
    "remote-workspace-load-all" : true
} 

![ftp-settings](https://user-images.githubusercontent.com/56134192/66157375-0c275600-e5fa-11e9-8e7d-1c42b9bac26d.png)

**Comment by humy2833** [comment]
I'm very sorry.
Please upgrade to version 0.7.2.

**Comment by ValmirGonzagaCosta** [comment]
The version was updated to 0.7.2 (image belwo), but the problem is the same. No work. Not recognize the directory and  I cant' see the ftp-simple in the "File - Preferences - Settings"
![ftp-update](https://user-images.githubusercontent.com/56134192/66202228-95cb3800-e67b-11e9-939a-bce03053b603.PNG)
