### ISSUE TITLE
Folders on server now display as documents?

### ISSUE THREAD

**Issue by LEXWORTHY** [humy2833/FTP-Simple#220]
Last week I finally got the configuration working and I was editing files live on the server. This week when I open "Open remote directory to workspace" the folders appear as files. 
![image](https://user-images.githubusercontent.com/35185798/66241968-4144ae80-e6b5-11e9-8009-fc7236a0d9e5.png)
This is not the case when I connect with Filezilla or other ftp clients. 
(Filezilla)
![image](https://user-images.githubusercontent.com/35185798/66242060-89fc6780-e6b5-11e9-8819-00c401385311.png)

**Comment by lucianomelotti** [comment]
I have the same issue

**Comment by ArjandenOuden** [comment]
same here, folders are displayed as files and vice versa.
Opening a (real) file results in error: 'no such directory'.

**Comment by juanoa** [comment]
same

**Comment by drumkilla** [comment]
Same issue after vscode update to 1.38.1.

**Comment by AutodataNederland** [comment]
same issue.. when is this fixed?

**Comment by emeiland** [comment]
same issue

**Comment by drumkilla** [comment]
After adding these lines to vscode settings.json extension works as expected.
`"ftp-simple.remote-workspace" : "c:/remote-workspace",
"ftp-simple.remote-workspace-load-all" : true`

**Comment by humy2833** [comment]
I'm so sorry I'm late.
Would you like to try the latest version again?

**Comment by LEXWORTHY** [comment]
Great. Working again. Thank you @humy2833

**Comment by LEXWORTHY** [comment]
@humy2833  I just noticed the nested directories are still having this issue. The first level directories are working though. http://prntscr.com/pjs3z7
