### ISSUE TITLE
vscode ftp-simple not found error

### ISSUE THREAD

**Issue by rkdwldnjs1** [humy2833/FTP-Simple#224]
안녕하세요, vscode에서 ftp-simple을 잘 사용하다가 어느 순간 부터 ftp-simple:config를 비롯한 모든 명령어들이 not found라고 뜨는데요. 어떻게 해결할 수 있을까요?

**Comment by humy2833** [comment]
구동 환경이 어떻게 되시나요?
vscode 열었을때 "Help - Toggle Developer Tools" 메뉴를 열었을때 에러가 나오는게 있다면 알려주실 수 있을가요?

**Comment by humy2833** [comment]
0.7.5 버전으로 올리시면 해결될겁니다.
불편을 드려 죄송합니다.

**Comment by gytjq456** [comment]
ftp 접속할때 파일이 DIR상태로 안받아지는 현상이 있는데 어떻게 해결해야할까요??
