### ISSUE TITLE
Running the contributed command: 'ftp.config' failed.

### ISSUE THREAD

**Issue by jaroslaw-filipiak** [humy2833/FTP-Simple#226]

**Comment by 4nt0n** [comment]
I have the same issue on
Version: 1.39.2
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:33:40.634Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 4.19.69-1-MANJARO

**Comment by rhys-vdw** [comment]
Yep. Non-starter for me too on macOS.

**Comment by humy2833** [comment]
Can you show me your error log?
Open "Help - ToggleDeveloper Tools" and you'll see.

**Comment by adsaurnab** [comment]
i also had the same problem but it got solved. It was just that a directory was missing.

C:\Users\user\AppData\Roaming\Code\User\globalStorage\humy2833.ftp-simple/ftp-simple.json 
 
:--- humy2833.ftp-simple/ftp-simple.json was missing from my computer

so crate a folder named: humy2833.ftp-simple
and then create the file: ftp-simple.json 
and then edit the file: 
[
    {
        "name": "anyname",
        "host": "yourhost",
        "port": "21",
        "type": "ftp",
        "username": "username",
        "password": "password",
        "path" : "/",
        "autosave": true,
        "confirm": false
    }
]

i think it happened after i reinstalled windows.
check if this solves your problem

**Comment by humy2833** [comment]
Sorry.
Please upgrade to version 0.7.5
