### ISSUE TITLE
'ftp.config' failed.

### ISSUE THREAD

**Issue by therkut** [humy2833/FTP-Simple#228]
Issue Type: <b>Bug</b>

Running the contributed command: 'ftp.config' failed.

Extension version: 0.7.4
VS Code version: Code 1.39.2 (6ab598523be7a800d7f3eb4d92d7ab9a66069390, 2019-10-15T15:35:18.241Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (5.86GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Gareth10jones** [comment]
I am also seeing this bug.  Am unable to run ftp.config which renders the plugin unusable :( Please fix ASAP.

**Comment by humy2833** [comment]
Can you show me your error log?
Open "Help - ToggleDeveloper Tools" and you'll see.

**Comment by humy2833** [comment]
Sorry.
Please upgrade to version 0.7.5
