### ISSUE TITLE
ftp-simple-temp.json File not found

### ISSUE THREAD

**Issue by jonatan-castaneda** [humy2833/FTP-Simple#24]
Hello!

I open the ftp-simple-temp.json so as to configure my own connections, I change the tab where is opened the json configuration file to another tab, then if I try back to the configuration file tab, VS Code gives the "file not found" error and closes the configuration file tab.

Operative System: Windows 10
Code version: 1.8.1

**Comment by humy2833** [comment]
This is a bug that occurred when VSCODE was upgraded.
(The "close" event occurs when you change the editor)
If VSCODE is modified later, it will be fixed automatically.
