### ISSUE TITLE
Editor scrolls to the top of the page when switching files

### ISSUE THREAD

**Issue by robbertstevens** [humy2833/FTP-Simple#25]
- VSCode Version: 1.8.1
- OS Version: Windows 10

Steps to Reproduce:

1. Open editor
2. Open multiple files
3. Scroll down
4. Switch file
5. Switch back to first file

**Comment by rubens268** [comment]
Yes please repair this!! 
I'm hating that :(

**Comment by Kleissner** [comment]
Same here, please fix this!
Thanks

**Comment by robbertstevens** [comment]
@humy2833  are you still developing this addon?

**Comment by ianfoulds** [comment]
Just forked this and posted a fix, makes the extension far more usable.

https://github.com/ianfoulds/FTP-Simple

**Comment by robbertstevens** [comment]
@ianfoulds Nice! Should I just clone ur repo? or are you also going to put in on the store/marketplace thingy?

**Comment by ianfoulds** [comment]
Hi Robert

Just clone it and push it as an update on yours. The only file changed is extension.js.

Regards

Ian Foulds
X.act Systems Ltd.
Mobile: 07976 871082

Web: http://www.x-act.co.uk<http://www.x-act.co.uk/> Tel: 01629 825092
Registered in England, Company no. 2717483.
Registered office: 6 Nan Gells Hill, Bolehill, Matlock, DE4 4GN

This message contains confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. E-mail transmission cannot be guaranteed to be secure or error-free as information could be intercepted, corrupted, lost, destroyed, arrive late or incomplete, or contain viruses. The sender therefore does not accept liability for any errors or omissions in the contents of this message, which arise as a result of e-mail transmission. If verification is required please request a hard-copy version.
