### ISSUE TITLE
FTP 접속이 불안하여 loading 안되네요

### ISSUE THREAD

**Issue by logicfeel** [humy2833/FTP-Simple#268]
Issue Type: <b>Bug</b>

ftp 원격작업 접근하면 

Please wait ... Remote info  ..... 이후

Remote Info downloading success.  <== 메세지가 안되고 실패합니다.

Extension version: 0.7.5
VS Code version: Code 1.53.0 (8490d3dde47c57ba65ec40dd192d014fd2113496, 2021-02-03T20:36:38.611Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor               (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (12.19GB free)|
|Process Argv|-n --crash-reporter-id 111abcda-08fe-42bb-87d1-c475e9108fc1|
|Screen Reader|no|
|VM|67%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30211402
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt600cf:30251589

```

</details>

**Comment by dev-whoan** [comment]
동일증상 있습니다. 얼마전부터 생긴 증상이네요

**Comment by rlfgh2002** [comment]
https://code.visualstudio.com/updates/v1_53
1.53 이나 1.52로 다운그레이드 해보세요

**Comment by dev-whoan** [comment]
@rlfgh2002 감사합니다. 1.52로 다운그레이드하니 괜찮게 연결 되네요. 1.53은 여전히 FTP 연결이 불안하네요.

**Comment by humy2833** [comment]
vscode 버전이 올라가며 일부 기능이 변경된것 같습니다.
0.7.6 버전에서 수정했습니다.
