### ISSUE TITLE
ftp-simple 파일 로딩 오류

### ISSUE THREAD

**Issue by lhs010106** [humy2833/FTP-Simple#269]
진짜 얼마전까지만 해도 잘 작동했는데 어느 순간을 기점으로 ftp-simple을 실행하면

Please wait......Remote Info downloading... You can see 'output console'

이 말만 나오고 열리지 않을때도 있고

제가 작업하는 파일들 목록은 나오는데 파일들이 로딩이 계속 안되기도 합니다.

혹시나 싶어서 비쥬얼 스튜디오를 삭제했다가 다시 깔았는데 처음 한번만 되고 그 다음부터는 위와 같은 오류가 

계속됩니다.... 어떻게해야하나요...?

**Comment by mack-erel** [comment]
#267 을 확인해보세요.

**Comment by humy2833** [comment]
vscode 버전이 올라가며 일부 기능이 변경된것 같습니다.
0.7.6 버전에서 수정했습니다.
