### ISSUE TITLE
파일 저장 후, 파일을 닫고 다시열면 내용이 비어있습니다.

### ISSUE THREAD

**Issue by yoonk-0** [humy2833/FTP-Simple#270]
ftp-simple을 잘쓰고 있었습니다.
작업하던 도중 파일 저장 후에 다시 파일을 열어보는데,
작성한 코드가 사라지고 내용이 없이 빈 화면으로 나옵니다.

vs-code를 다시 설치해보고, ftp-simple도 삭제 후
재설치해보아도 똑같은 현상이 있습니다.

답변 주시면 감사하겠습니다!

**Comment by Kiloop2020** [comment]
I have the same problem

**Comment by Kiloop2020** [comment]
@yoonk-0 이 버전의 vscode를 사용하는 것 사이의 해결책을 제공하기 위해 번역기를 사용하고 있습니다. https://code.visualstudio.com/updates/v1_50

**Comment by rlfgh2002** [comment]
https://code.visualstudio.com/updates/v1_53
1.53이나 1.52로 다운그레이드 하니까 저는 제대로 되네요

**Comment by yoonk-0** [comment]
> I have the same problem

Thank you for your answer.
I think there was a problem because of the vscode version update.
I deleted FTP-SIMPLE extension and newly installed FTP-SYNC extension.

**Comment by humy2833** [comment]
vsocde 버전이 올라가며 일부 기능들이 변경이 된것 같습니다.
0.7.6 버전에서 수정했습니다.
