### ISSUE TITLE
Stop downloading file when open in workspace

### ISSUE THREAD

**Issue by smerinohpe** [humy2833/FTP-Simple#272]
I was working with the extension without problem, and suddenly the extension is stop working when I use 'open to workspace' because not download files when open it...

**Comment by rlfgh2002** [comment]
vs code version downgrade 1.53 or 1.52 
https://code.visualstudio.com/updates/v1_53

**Comment by smerinohpe** [comment]
Tested with with both with same results

**Comment by smerinohpe** [comment]
[Video example](https://drive.google.com/file/d/1yYLeYkNUrAwEUNqEwe2nvTpKOg-uUNdd/view?usp=sharing) with the problem.

**Comment by humy2833** [comment]
The vscode has been upgraded and some features seem to have been removed.
Fixed in version 0.7.6(__)

**Comment by smerinohpe** [comment]
Working again.... 🎉🎉🎉

Thank you
