### ISSUE TITLE
1.54이후 버전에서 파일 다운도르 안되요

### ISSUE THREAD

**Issue by redfaceyol** [humy2833/FTP-Simple#274]
1.54 이후 버전에서 발생되는 문제입니다.
파일 저장 후 로컬의 파일을 보면 0kb로 변경이 되는데, 
다시 열때 다운로드를 하지 않아 빈 파일이 그대로 열립니다.
그러나 1.53버전에서는 파일 오픈시 다운로드를 해 서버 파일의 내용으로 열립니다.

**Comment by humy2833** [comment]
vscode 버전이 올라가며 제거된 기능들이 있었나보네요.
0.7.6 버전에서 수정했습니다(__)
