### ISSUE TITLE
Default path for Save file command

### ISSUE THREAD

**Issue by michalhudecek** [humy2833/FTP-Simple#3]
Why is the default path for saving file always the root? It is very time consuming to go through all the folders until I find the correct one. The default path should be derived from the current path of the file (=path from settings + "/" + relative path of the file).

![image](https://cloud.githubusercontent.com/assets/1215304/18049810/d8ab3b28-6dea-11e6-92c4-479cd48aa1c2.png)

**Comment by humy2833** [comment]
Sorry. Unfortunately this module is not the synchronization module project.
This is because only the common FTP.
For example, the working file must be saved In every path.

**Comment by michalhudecek** [comment]
I don't need synchronization. I just want to save the current file manually to the proper path on FTP without manually going to the path again.

**Comment by humy2833** [comment]
please accept again the latest version.
Use config option "project" 
thank you.
