### ISSUE TITLE
Error Config connection setting resulted in an error "Reading '0"

### ISSUE THREAD

**Issue by Gagepower** [humy2833/FTP-Simple#322]
![Screenshot 2024-09-06 131321](https://github.com/user-attachments/assets/707d9c1d-892f-438c-ab84-331246545d27)

Receiving this error when trying to run any command on command pallet.
The only thing I did before hand was recover a html autosave, its been working for weeks until now,
I have reinstalled Visual Code & the plugins multiple times, restarted multiple times.
Tried to create a new json file, but to no avail.

**Comment by lijom80** [comment]
Same issue - tried everything still including uninstall/reinstall or ftp-simple, vscode, deleted AppData\Roaming\Code\User\workspaceStorage still the problem continues to occur
![image](https://github.com/user-attachments/assets/f26afbbd-bee7-4c8d-b244-f8836edbff1f)

**Comment by Cr0phiXx** [comment]
Happened last night to me right after vscode updated itself to v1.93.0.
Tried reinstalling, setting up a new config and deleting.
AppData\Roaming\Code\User\workspaceStorage

**Comment by lijom80** [comment]
> Happened last night to me right after vscode updated itself to v1.93.0. Tried reinstalling, setting up a new config and deleting. AppData\Roaming\Code\User\workspaceStorage

did it fix. I tried it and did not solve

**Comment by Cr0phiXx** [comment]
> > Happened last night to me right after vscode updated itself to v1.93.0. Tried reinstalling, setting up a new config and deleting. AppData\Roaming\Code\User\workspaceStorage
> 
> did it fix. I tried it and did not solve

No, i have not found a solution yet

**Comment by tawissus** [comment]
I have the same problems and have just wasted over an hour.

With the old version 1.92.2 everything works again (until the next update).

https://vscode.download.prss.microsoft.com/dbazure/download/stable/fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/VSCodeUserSetup-x64-1.92.2.exe

Very annoying.

**Comment by Cr0phiXx** [comment]
> I have the same problems and have just wasted over an hour.
> 
> With the old version 1.92.2 everything works again (until the next update).
> 
> https://vscode.download.prss.microsoft.com/dbazure/download/stable/fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/VSCodeUserSetup-x64-1.92.2.exe
> 
> Very annoying.

I was about to switch to another ftp-plugin but downgrading is easier. Thanks for the link!
You can disable auto-updates for vscode. Klick the bottom Left settings Button, then head to settings -> Application.

![img-2024-09-06-10-50-03](https://github.com/user-attachments/assets/d2e5c69a-aa83-4669-87eb-dee52ad76b42)

**Comment by Gagepower** [comment]
> > I have the same problems and have just wasted over an hour.
> > With the old version 1.92.2 everything works again (until the next update).
> > https://vscode.download.prss.microsoft.com/dbazure/download/stable/fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/VSCodeUserSetup-x64-1.92.2.exe
> > Very annoying.
> 
> I was about to switch to another ftp-plugin but downgrading is easier. Thanks for the link! You can disable auto-updates for vscode. Klick the bottom Left settings Button, then head to settings -> Application.
> 
> ![img-2024-09-06-10-50-03](https://private-user-images.githubusercontent.com/72713844/365099702-d2e5c69a-aa83-4669-87eb-dee52ad76b42.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MTMwMTQsIm5iZiI6MTcyNTYxMjcxNCwicGF0aCI6Ii83MjcxMzg0NC8zNjUwOTk3MDItZDJlNWM2OWEtYWE4My00NjY5LTg3ZWItZGVlNTJhZDc2YjQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDA4NTE1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyYThkNDIxNmRjOTg4ZGFhZTRhNDNlODA5Njg5Y2NkYWEyN2M2MjUyMGY5MjllOTk1NGVkODdhMWU3NjgxZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.g1fpJEKIOJkwvHAzhv26ze7wqIVC-A2iYbG7wB4SAMs)

I did this about an hour ago after wasting like 4 hours of time...

This is the answer

**Comment by j1eun-2** [comment]
> I have the same problems and have just wasted over an hour.
> 
> With the old version 1.92.2 everything works again (until the next update).
> 
> https://vscode.download.prss.microsoft.com/dbazure/download/stable/fee1edb8d6d72a0ddff41e5f71a671c23ed924b9/VSCodeUserSetup-x64-1.92.2.exe
> 
> Very annoying.

thanks a lot!!! I have same problem as well. but It is getting working right now.

**Comment by tawissus** [comment]
Hopefully there will be a fix soon.

**Comment by tawissus** [comment]
The ticket should not be closed. Either the extension needs an update or VSCode.

**Comment by Cr0phiXx** [comment]
Microsoft is not going to do anything about the compatibility of a plugin and the ftp-simple plugin had it's last update in 2021.
So i dont think there will be anything done about this issue, but i can be wrong!

Best bet would be to carry on with another ftp plugin like ftp-kr or to stay at version 1.92.2. Whereas i dont recommend not updating your software.

**Comment by tawissus** [comment]
FYI
https://github.com/microsoft/vscode/issues/227743

**Comment by yunusga** [comment]
https://github.com/humy2833/FTP-Simple/issues/324#issuecomment-2335189454 hotfix
