### ISSUE TITLE
'ftp-simple : Config - FTP connection setting' resulted in an error Cannot read properties of undefined (reading '0')

### ISSUE THREAD

**Issue by mrAmrish** [humy2833/FTP-Simple#323]
Hello Sir on opening _ftp-simple config ftp connection setting_ it shows this error ,already fresh installed  vs code on macbook pro sonomo again tried same results.
added a screentshot
![Screenshot 2024-09-06 at 4 23 23 PM](https://github.com/user-attachments/assets/d752518a-adb1-4a68-a79a-75f3921dc7d7)

**Comment by agalizi** [comment]
Same problem here: fresh install and "Cannot read properties of undefined"; tried uninstall, change directory, recovered old json from a backup but no success.

**Comment by rastogiaman1998** [comment]
Same problem Here also , it was working properly but from today it stopped working first , it make config file corrupt and after some reinstalling it start work but when i start loading the ftp data it again corrupt the config data

**Comment by Th3oX** [comment]
I am experiencing the same issue. I have attempted to reinstall Visual Studio Code entirely without any extensions and also tried disabling my antivirus, but nothing has resolved the problem.

**Comment by alexsantaconcha** [comment]
Same problem here

**Comment by n00bkavesh** [comment]
i also got messed up with this issue ,but after 2-3 hours i got my answere ,its as simple as mixing flour, sugar, and eggs just downgrade you **_Vs code editor to Version: 1.92.2_**
And done no worry

**Comment by wrickout** [comment]
After updating 1.93.0 the ftp-simple. json  changed to random characters and numbers.
If i copy the sample it says check simple-ftp config syntax.
![image](https://github.com/user-attachments/assets/38bdb840-fea5-4858-a58e-32f26e3e1fef)

**Comment by gain0904** [comment]
https://code.visualstudio.com/updates/v1_92

**Comment by AdrianoBarbosa** [comment]
Same issue here. I installed SFTP by Natizyskunk, and now ftp-simple is working again. Maybe it's not the best solution, but at least I can work again.

**Comment by dskoczylas** [comment]
Same problem here, after last update:
 
![image](https://github.com/user-attachments/assets/02ead30a-27f9-4516-af3b-ebd7a877c486)

**Comment by RosyVelasquez** [comment]
> https://code.visualstudio.com/updates/v1_92

IT WORK!!! Thanks <3

**Comment by JoeyStip** [comment]
> Same problem here, after last update:
> 
> ![image](https://private-user-images.githubusercontent.com/92728373/365210981-02ead30a-27f9-4516-af3b-ebd7a877c486.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2NDYyMjksIm5iZiI6MTcyNTY0NTkyOSwicGF0aCI6Ii85MjcyODM3My8zNjUyMTA5ODEtMDJlYWQzMGEtMjdmOS00NTE2LWFmM2ItZWJkN2E4NzdjNDg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDE4MDUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4MjI2ZWE1ODAwNzNmNjkyZjg1OWUzZGJkZDUwYWI0NjczMzJjYmUxNDA5YjVhZTAwMDQwYmVjYWQ0ZGY2MTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ebSis4y8X1CANb-3BGG0aH2J8bQVALGd1QXV-YIgdz8)

I got the same exact error despite it working for me yesterday.

**Comment by mrAmrish** [comment]
> i also got messed up with this issue ,but after 2-3 hours i got my answere ,its as simple as mixing flour, sugar, and eggs just downgrade you **_Vs code editor to Version: 1.92.2_** And done no worry

Thanks alot n00bkavesh ,now it's up I am right on track

**Comment by mrAmrish** [comment]
> i also got messed up with this issue ,but after 2-3 hours i got my answere ,its as simple as mixing flour, sugar, and eggs just downgrade you **_Vs code editor to Version: 1.92.2_** And done no worry
Thanks alot n00bkavesh now it's up and running

**Comment by mrAmrish** [comment]
> https://code.visualstudio.com/updates/v1_92

Sorry bro ihe link is not working ,you have to downgrade v1.92.2

**Comment by mrAmrish** [comment]
> After updating 1.93.0 the ftp-simple. json changed to random characters and numbers. If i copy the sample it says check simple-ftp config syntax. ![image](https://private-user-images.githubusercontent.com/15617835/365168410-38bdb840-fea5-4858-a58e-32f26e3e1fef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2NDgzMDIsIm5iZiI6MTcyNTY0ODAwMiwicGF0aCI6Ii8xNTYxNzgzNS8zNjUxNjg0MTAtMzhiZGI4NDAtZmVhNS00ODU4LWE1OGUtMzJmMjZlM2UxZmVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDE4NDAwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmY2U5OTEzM2QxNmFmMDUzZTZiOGMzNTljOThmOTk2YmFmYzU5MTQzY2Q2NjA1MmFkZTUxNDU0YjUxZDFiYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gOux8qDkKRG4eLLF-I7olpDXAJS1QiT04M75Uh4yL40)

https://github.com/humy2833/FTP-Simple/issues/323#issuecomment-2333945825

**Comment by mrAmrish** [comment]
> Same issue here. I installed SFTP by Natizyskunk, and now ftp-simple is working again. Maybe it's not the best solution, but at least I can work again.

Try this
https://github.com/humy2833/FTP-Simple/issues/323#issuecomment-2333945825

**Comment by mrAmrish** [comment]
> i also got messed up with this issue ,but after 2-3 hours i got my answere ,its as simple as mixing flour, sugar, and eggs just downgrade you **_Vs code editor to Version: 1.92.2_** And done no worry

🙏 thanks

**Comment by mrAmrish** [comment]
For vs code future release fto-simple has to release a supported version

**Comment by kordostomas** [comment]
> i also got messed up with this issue ,but after 2-3 hours i got my answere ,its as simple as mixing flour, sugar, and eggs just downgrade you **_Vs code editor to Version: 1.92.2_** And done no worry

Well Thanks this works. But how do I keep vs code from updating? I switched the update mode to none and it asked me to restart and it literally updated that moment.

**Comment by yunusga** [comment]
https://github.com/humy2833/FTP-Simple/issues/324#issuecomment-2335189454 hotfix
