### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by Divix01** [humy2833/FTP-Simple#4]
It does not work with large projects, only local tests? )
After connection (ftp data is correct, checked): http://prntscr.com/cdh6xl - is wrong

Maybe mode? Where can I set mode?

**Comment by Divix01** [comment]
I get an error when trying open remote directory in wokspace. "The path does not exist" in %appdata%/...

**Comment by humy2833** [comment]
Open Remote Directory function can be activated only once. If the working directory is changed or closed, the temporary file is deleted, re-open functionality must run the remote directory. Later we will look to add additional functionality. Thanks.

**Comment by Divix01** [comment]
No. The new machine, other OS, one working ftp with large files, a new empty directory in the workspace and error.

**Comment by humy2833** [comment]
please accept again the latest version.
thank you.

**Comment by Divix01** [comment]
NICE!
