### ISSUE TITLE
Change encoding for remote unix files

### ISSUE THREAD

**Issue by stefanokiedis** [humy2833/FTP-Simple#42]
Hi,
thank you for your beautiful "simple-ftp" extension for Visual Studio Code editor.
Can I save or create/modify a remote file with ISO 8859-1 encoding (that is our company common encoding for files)?
I've seen that my remote files taken with simple-ftp from a Unix ftp-server have all UTF-8 encoding and I can't change the encoding to ISO 8859-1.
So, dislike for example from NotePad++ editor ftp plugin, I see simbols (like this: �) instead all special characters.
This is a problem for us when we compare our modified remote files with original repository files: lots of differences are due only to different encoding!!! (look at the screenshot below)
![immagine](https://cloud.githubusercontent.com/assets/27360614/24965162/906a6986-1fa3-11e7-9b49-5d6225c4487c.png)

Thank you
Stefano

**Comment by humy2833** [comment]
Please accept again the latest version.(0.4.18 or higher).
Then set the remote workspace options.

**Comment by stefanokiedis** [comment]
Thank you for fix.
Now with "Remote Directory" function it works fine!!!

But the bug of encoding is still there when I use "*Open the file directly
from FTP*" function (see the screenshot below).
In fact, I have noticed that when I open remote files with this very
comfortable function, the temporary remote path of files is longer... the
same remote path before your fix.

Furthermore:
Is it normal that in the setting.json file I have an error when I put your
new config line "ftp-simple.remote-workspace" : "c:/remote-workspace"??
(see the same screenshot below).

Thank you in advanced!
Stefano

[image: Immagine incorporata 3]




2017-05-08 3:10 GMT+02:00 YoungJae Lee <notifications@github.com>:

**Comment by humy2833** [comment]
Be careful of the "json" grammar.

example)
"editor.renderWhitespace" : "all",
"ftp-simple" : {
        "remote-workspace" : "c:/remote-workspace"
},
