### ISSUE TITLE
No notifications if upload was completed

### ISSUE THREAD

**Issue by edarioq** [humy2833/FTP-Simple#46]
I don't see a notification of completed when I save to server via FTP.

**Comment by humy2833** [comment]
Activate " Output " with " Ctrl + Shift + U ".

**Comment by edarioq** [comment]
Hi, nothing happens when I use that shortcut.

**Comment by edarioq** [comment]
Nevermind, for Mac is ⇧⌘U - Thanks!

**Comment by edarioq** [comment]
I got it... you have to select the dropdown ftp-simple.
<img width="339" alt="screenshot 2017-05-09 08 19 56" src="https://cloud.githubusercontent.com/assets/1882457/25852832/55bfc658-3490-11e7-8cdc-9750789c7d44.png">
