### ISSUE TITLE
subfolder is not downloaded

### ISSUE THREAD

**Issue by jianghuitao** [humy2833/FTP-Simple#49]
Upgrade to 0.4.17, subfolder is not downloaded but a file named "[DIR] folder name" with zero bytes. When clicking the "[DIR] folder name", the folder is downloaded, but [DIR] is not listed in the parent folder any more, until relaunching VS-Code.

**Comment by humy2833** [comment]
There was a lot of modification since loading the entire file at once was slow.
Therefore, the subfolders were displayed as [DIR], and only clicked folders were modified to load.

**Comment by raitaionut** [comment]
Same Issue Here. Can you provide us a downgraded version untill you will solve this one ?

**Comment by sevensins** [comment]
Can we have a downgraded please version till this is resolved ?
On clicking now the folders disappear.

**Comment by humy2833** [comment]
Clicking on the folder will load the files in the folder.
There is a bug that VSCode does not refresh automatically.
You can click Refresh yourself.

**Comment by foverzar** [comment]
Unfortunately, for me clicking on [Dir] files does not result in downloading subfolders -- [Dir] files are just removed. I even checked remote-workspace-temp directory -- new folders are not created.

**Comment by KyleDumas** [comment]
For everyone trying to get this plugin working you can use a temporary fix by replacing your the plugin extension.js with the 0.4.16 version:
https://github.com/humy2833/FTP-Simple/blob/9c301b8ee0b97abd91eeafd1bf108bfdb27e8f19/extension.js

**Comment by SubGothius** [comment]
I'm seeing the same behavior as @foverzar -- clicking a [DIR] subfolder just makes it disappear, and it does not reappear after refreshing the File Explorer.

**Comment by humy2833** [comment]
Sorry. 0.4.21 fixed.
If you still have problems, try deleting the workspace and try again.
