### ISSUE TITLE
Not closing connections on Mac OS

### ISSUE THREAD

**Issue by niklasfink** [humy2833/FTP-Simple#53]
FTP-Simple is not closing connections on Mac OS. That means probably for every opened file a new connection to the FTP is made. Since they are not getting closed, the FTP remains with an enormous amount of unclosed connections and will throw "too many connections" at one time which is not interpreted by FTP-Simple so it only shows "FTP Connecting".

**Comment by humy2833** [comment]
The ftp connection is used as a singleton.
The FTP connection is terminated when the connection time expires or VSCode is terminated.
