### ISSUE TITLE
No Ftp-Simple settings available

### ISSUE THREAD

**Issue by fedeverdi** [humy2833/FTP-Simple#55]
I can't setting "remote-workspace-load-all" : true because vsCode tell me "Unknown configuration settings" for ftp-simple ...

Ideas ?

**Comment by humy2833** [comment]
Ignore it.

**Comment by fedeverdi** [comment]
Yes but settings doesn't works ....

**Comment by humy2833** [comment]
Show me your settings.

**Comment by fedeverdi** [comment]
{
    "terminal.integrated.shell.osx": "/bin/zsh",
    "editor.renderWhitespace": "none",
    "editor.minimap.enabled": true,

    "ftp-simple" : {
        "remote-workspace-load-all" : false
    }
}

**Comment by cchang62** [comment]
![image](https://user-images.githubusercontent.com/15147139/32715704-5bfe3134-c88e-11e7-8736-53e9ed018906.png)
Here is my settings. I also get the same problem. In turn, I can't search a string in all files of a directory.
