### ISSUE TITLE
Any Way to Select Binary Transfer Mode?

### ISSUE THREAD

**Issue by bgarrant** [humy2833/FTP-Simple#58]
I am wondering if there is a way to select binary for the transfer mode?  I am having issues connecting to PureFTP servers due to the double line feed issue you can read about on https://winscp.net/eng/docs/faq_line_breaks#known_issues.  If you can force binary mode then Windows users can connect to pure-ftp servers.  Is it possible to add this feature?

**Comment by humy2833** [comment]
The ftp module I used is in binary mode by default.
The modules used internally are as follows.
[ssh2](https://www.npmjs.com/package/ssh2), [jsftp](https://www.npmjs.com/package/jsftp)
