### ISSUE TITLE
Delete 명령 수행 시 서버쪽 파일이 삭제가 되지 않습니다.

### ISSUE THREAD

**Issue by junisara** [humy2833/FTP-Simple#59]
좋은 프로그램을 제공해 주셔서 정말 감사드립니다.
저만 그런건지 모르겠지만 DEL 명령어를 실행 시키면 로컬에서는 삭제가 되는데 서버에서는 삭제가 되지 않는것 같습니다.  Notepad++에 있는 FTP로 똑같이 접속해서 삭제를 하면 삭제가 잘 되는것으로 봐서 FTP서버 설정문제같지는 않아서요..  제가 설정부분에서 놓친 부분이 있을까요?

**Comment by humy2833** [comment]
이런 허접한걸 이용해주셔서 감사합니다(__)

원격 파일은 일부로 DEL 키로 서버상의 파일까지 삭제하지 않게 하였습니다.
처음에는 그러하게 했었는데 워낙 다양한 사람들이 쓰니까 다 취향이 달라서 그런지 반발 또한 있었습니다.
(삭제 했는데 서버 상에서 파일이 날라 갔다는 사람이 있더라고요......--;;)
그래서 삭제 기능만은 별도로 삭제할 파일, 폴더에 마우스 우클릭 하여서 
"ftp-simple : Delete ... " 를 통해서만 로컬과 서버 둘다 삭제하실 수 있습니다.
더 궁금하신거나 건의, 버그 등이 있으면 언제든지 말씀해주세요.

**Comment by junisara** [comment]
답변 감사드립니다. 꾸벅 (_.._)

말씀해주신 "ftp-simple : Delete ... " 로 삭제명령어를 사용했으나 서버에서 삭제가 되지않아서 말씀 드린것이였습니다.
삭제를 했으나 계속 리스트에 남아 있네요


2017. 5. 25. 오후 12:47에 "YoungJae Lee" <notifications@github.com>님이 작성:

이런 허접한걸 이용해주셔서 감사합니다(__)

원격 파일은 일부로 DEL 키로 서버상의 파일까지 삭제하지 않게 하였습니다.
처음에는 그러하게 했었는데 워낙 다양한 사람들이 쓰니까 다 취향이 달라서 그런지 반발 또한 있었습니다.
(삭제 했는데 서버 상에서 파일이 날라 갔다는 사람이 있더라고요......--;;)
그래서 삭제 기능만은 별도로 삭제할 파일, 폴더에 마우스 우클릭 하여서
"ftp-simple : Delete ... " 를 통해서만 로컬과 서버 둘다 삭제하실 수 있습니다.
더 궁금하신거나 건의, 버그 등이 있으면 언제든지 말씀해주세요.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/humy2833/FTP-Simple/issues/59#issuecomment-303914822>,
or mute the thread

**Comment by humy2833** [comment]
헛....혹시 콘솔창에 어떻게 나오는지 알 수 있을까요?
정상적이라면 delete 로그가 떠야하는데....
콘솔은 Ctrl + Shift + U 로 열 수 있습니다.

**Comment by junisara** [comment]
이게.. 삭제뿐만이 아니고 폴더 생성도 되지 않네요.
write권한이 없어서 그런가 하고 봤는데.. 권한은 있습니다.

파일은 업로드가 되는데..
폴더가 업로드 및 생성이 되지 않습니다.

2017. 5. 25. 오후 2:37에 "juni sara" <junisara@gmail.com>님이 작성:

**Comment by humy2833** [comment]
음...이상하네요 전 테스트해도 잘 되는데....
원격 폴더를 작업 폴더로 해놓고 하시는건데 그런거죠?
콘솔 로그도 잘 찍히고요.....
혹시 폴더나 파일이 한글명 인가요?

**Comment by junisara** [comment]
파일명과 폴더명은 영문입니다.
네.. 제 ftp 서버 설정이 문제일수도 있겠네요.
알겠습니다. 감사합니다.


2017. 5. 25. 오후 4:13에 "YoungJae Lee" <notifications@github.com>님이 작성:

음...이상하네요 전 테스트해도 잘 되는데....
원격 폴더를 작업 폴더로 해놓고 하시는건데 그런거죠?
콘솔 로그도 잘 찍히고요.....
혹시 폴더나 파일이 한글명 인가요?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/humy2833/FTP-Simple/issues/59#issuecomment-303941009>,
or mute the thread

**Comment by humy2833** [comment]
실력이 부족해 도움이 되지 못하여 죄송합니다(__)

**Comment by junisara** [comment]
아닙니다. ^^
충분히 감사하고 쓰고 있습니다.
감사합니다.

2017. 5. 25. 오후 4:34에 "YoungJae Lee" <notifications@github.com>님이 작성:
