### ISSUE TITLE
Open Folder on "remote directory open to workspace"

### ISSUE THREAD

**Issue by meriturva** [humy2833/FTP-Simple#6]
I just use command `remote directory open to workspace` but i cannot open subfolder correctly showed on left view 'file explorer'.
Anyway to open folders and subfolders?

**Comment by humy2833** [comment]
oh, sorry.
I fixed bug issue.
Please accept again the latest version. 
Thanks.

**Comment by meriturva** [comment]
It works! just a short question....folders structure is explored just on start process or when user click on single folder.

**Comment by rodserrano** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/56070931/66035964-bb9ef280-e53e-11e9-8392-2febaa06c7f3.png)

Same issue I encounter but I already update it.
