### ISSUE TITLE
Feature request: Sync command

### ISSUE THREAD

**Issue by ArvidBaa** [humy2833/FTP-Simple#63]
Is it possible to add "sync up" ad "sync down" to the available commands? I would like to sync the entire project directory, and download (for sync down) and upload (for sync up) all files that differ.

**Comment by humy2833** [comment]
You can download the entire project or upload it.
project download = sync down
project up = sync up

**Comment by ArvidBaa** [comment]
No, that is not what I'm asking for. Project download will download ALL files, while I only want to download NEW and CHANGED files. I also want to delete all local files that has been deleted on the server. In other words - sync. During the sync I also want to be able to see all files that will be changed (locally for sync down and remotely for sync up), and be able to compare them.

The download option should also (as of #61 ) only download the active or selected file/folder, and will therefore not work either as project sync or project download.

**Comment by ArvidBaa** [comment]
I would really like it if you could have another look at this. Simply put:
project download =/= sync down
project up =/= sync up

Project download = download all files (or just the selected file)
Sync down = download changed and new files
And vice versa for upload.

**Comment by ArvidBaa** [comment]
Could you please consider reopening this ticket?
