### ISSUE TITLE
Remote dir open: All files downloaded with zero bytes

### ISSUE THREAD

**Issue by TonyGravagno** [humy2833/FTP-Simple#73]
v0.5.2 over Windows. In VS Code, Preferences, Settings, I've added:
```
    "ftp-simple": {
        "remote-workspace" : "C:/Development/VSCode"
    }
```
Now Remote Directory Open to Workspace. All files and folders load under that path, but there is no content. All files have zero bytes. Without that setting all folders and files download as expected to the default folder. The remote-workspace-load-all flag set to true does not affect this.

EDIT: It does't matter that the remote-workspace was set. Looking at my %APPDATA% folder tree I see that all files are loaded with zero bytes. But if I use the default workspace folder I can see the data in VS Code. The doc says the remote-workspace-load-all default value is true but it's behaving like it's false.

**Comment by humy2833** [comment]
The "remote-workspace-load-all" option determines whether all child files will be received when opening a remote file.
It has nothing to do with the file size.
The file contents are loaded at the time of activation of the file.

**Comment by dordio** [comment]
I'm having the same issue only I haven't messed with the configuration options. Since I reinstalled ftp-simple this is what it does, creates the folder to receive the remote files, creates the files, but all are 0 bytes in size.

**Comment by TonyGravagno** [comment]
@dordio , what @humy2833 is telling us is that the files load with zero bytes but then they "should" be loaded on demand when we try to use them from the IDE rather than from outside. The reason I noticed it was zero bytes was because this lazy loading wasn't working for me. You?

@humy2833 do we need to do something else to get it to lazy load?

**Comment by humy2833** [comment]
If you want to receive the file completely, please use "download".
As mentioned above, the function "Remote directory open to workspace" is not a function.
You are misunderstanding and using features.

**Comment by dordio** [comment]
@humy2833 I don't want to receive the file, I wan't "**remote directory open to workspace**" to display the contents of the files it downloads. Please continue reading for a better explanation.

@TonyGravagno I'm not trying to open the files from outside the IDE. What I'm saying is: when I use "**remote directory open to workspace**" everything works fine, no errors at all, but all the files show up empty. When I select them in the Explorer sidebar, a tab shows up with the correct file name, but no content is display, same if I double click the file in the Explorer sidebar.
Here's a screenshot of what I'm describing:
![problem](https://user-images.githubusercontent.com/3708447/28936693-61512ab4-7880-11e7-8423-8499e117fcfe.jpg)
The list on the left is a live website from one of my clients. The open file "index.html" **HAS** content, but VS Code display nothing.

This started to happen a few days back on one of my Windows 10 machines and on a Macbook, I have a Dell laptop with Windows 10 wich is working just fine. All three have the latest version of VS Code and FTP-Simple. I have not messed with any option except the following:

> {
    "workbench.startupEditor": "newUntitledFile",
    "workbench.iconTheme": "vscode-great-icons",
    "editor.fontSize": 14,
    "editor.wordWrap": "on",
    "php.executablePath": "C:\\Program Files\\php7\\php.exe",
    "php.validate.executablePath": "C:\\Program Files\\php7\\php.exe",
    "php.validate.run": "onType"
}

Thank you all in advance for your help.

**Comment by TonyGravagno** [comment]
@dordio my understanding is the same as yours about what this thing should do. @humy2833 is telling us we're too stupid to understand how it works and he doesn't take that as a hint to maybe explain it better.

I'm going to close this request. I really don't care about what this developer does with his plugin. @dordio, if you want to pursue the matter, I recommend a separate ticket where you try to get the author to explain his functionality in code comments. Then it will be more clear to all involved as to whether this is actually a bug or not.

Good luck. I'm outta here.

**Comment by humy2833** [comment]
I do not understand English and I got help from a translator.
I sincerely apologize for this.

First, "remote ... open" function is displayed as 0byte by default and the contents are loaded when opening the file.
And when you open the workspace with the "remote ... open" function, you get all the files on the server, so the more files you have, the longer it takes to load. This loading appears in the "output" window (ctrl + shift + U).
Did you see any messages in the "ouput" window when you clicked index.html?

**Comment by mdcom77** [comment]
The above explanation works as explained if you are not using "ftp-simple.remote-workspace": option. When it is used, the empty structure is not downloaded as a whole, but only small part (1st level files) of the project.

**Comment by dafp18** [comment]
@humy2833 hace ratico que tengo el mismo inconveniente que describe @dordio los archivos descargan y el editor indica que se han descargado con exito, pero al momento de elegir un archivo para editarlo se queda en blanco, y si miro en la consola del ftp-simple, dice archivo descargado, pero sigue sin mostrar informaciòn y ahi puede quedarse mucho tiempo y no muestra el codigo, el pluging iba super bien actualmente estoy usando la version de vsc 1.35, y el ftp 0.7.0 pero no funciona, recuerdo que al momento de la instalacion tenia la version de vsc 1.32 y apesar de haber probado con las distintas versiones entre visual y ftp simple el problema no se resuelve, yo lo usaba a traves de la opcion remote directory open to workspace, pero no sè que sucedio y la verdad me parecia una extension muy buena...
