### ISSUE TITLE
followed the steps , not working , I'm assuming that its failing silently ?

### ISSUE THREAD

**Issue by a-eid** [humy2833/FTP-Simple#81]
I configured it as per the repo , and I'm trying to connect , but nothing ...
nothing happens , not loading , no connecting , 

after selecting the ftp server name ,.. nothing .

**Comment by humy2833** [comment]
You can see output console. 
Output console is "ctrl + shift + U". 
What does the console display?

**Comment by Sycend** [comment]
Same here, empty console, too.
What should happen?

**Comment by humy2833** [comment]
Is the setting correct?
Does it work with other FTP tools?
Can you show me the settings?

**Comment by Sycend** [comment]
Found the issue.
Used the wrong URL format at the host adress field.
Its:
yourFTPAdress.com
and not:
ftp://yourFTPAdress.com

Now it works just fine.
