### ISSUE TITLE
Already exist file overwrite?

### ISSUE THREAD

**Issue by sandrig** [humy2833/FTP-Simple#83]
Is there a way to stop being prompted about overwriting a newer file, and just allow the editor to overwrite it without asking?
Version Visual Studio Code 1.15.0 (1.15.0)
Mac OS
Screenshot http://joxi.ru/KAx79Ngt4vqqY2

**Comment by humy2833** [comment]
You can set the "confirm" value to "true" in the configuration.

**Comment by sandrig** [comment]
I used "autosave": true, "confirm": true in ftp-simple-temp.json

**Comment by humy2833** [comment]
Oh I am so sorry.
It is "false" instead of "true".
I made a mistake.

**Comment by sandrig** [comment]
Thanks, it's worked
